graph TD
  chayimme[chayimme]
  theobasis[theobasis]
  glossame[glossame]
  kimance[kimance]
  kimme[kimme]
  oriance[oriance]
  panimaance[panimaance]
  shemme[shemme]
  artiance[artiance]
  candence[candence]
  dokimance[dokimance]
  drujme[drujme]
  emetme[emetme]
  barzakhqing[barzakhqing]
  britqing[britqing]
  darshanqing[darshanqing]
  daseinqing[daseinqing]
  devekutqing[devekutqing]
  barakqing[barakqing]
  doxomme[doxomme]
  epiclance[epiclance]
  hallance[hallance]
  heurekin[heurekin]
  ethosme[ethosme]
  hastame[hastame]
  jinsme[jinsme]
  morphame[morphame]
  noemame[noemame]
  theobasis ---|L1→L2| glossame
  glossame ---|L2→L3| kimance
  kimance ---|L3→L4| dokimance
  dokimance ---|L4→L5| kinqing
  kinqing ---|L5→L6| inim
  inim ---|L6→L7| noemame
  theobasis ---|L1 family| chayimme
  kinqing ---|L5 family| walkekin
  shemme ---|-me family| kimme
  barakqing ---|-qing family| zakarqing
